# OCR settings: "tesseract", "easyocr", or "custom"
ocr:
  engine: custom
  
  # only used by tesseract
  tesseract_cmd: /usr/bin/tesseract
  lang: urd

  # only used if engine: custom
  model_path: /app/app/models/cnn_gru_model.h5

  # only used by easyocr
  # gpu: false

# TTS settings
tts:
    language: ur-PK
    audio_encoding: MP3
    model_id: eleven_multilingual_v1
    voice_id: pNInz6obpgDQGcFmaJgB
    api_key: 
    voice_settings:
      stability: 0.7            # smoother speech
      similarity_boost: 0.85    # closer to the original voice tone